### PR TITLE
Update Rust nightly version

### PR DESCRIPTION
**Pull request by wangrunji0408**
## Major changes
* Update Rust nightly to 2020-01-17.
* Disable hard-float on mips and export-dynamicon aarch64 due to LLVM bug.
* Update smoltcp and fix drivers for API change. (not tested)
* Fix a data racing bug on thread crate.

## Minor changes
* Update riscv `atomic.patch`, the old one no longer works.
* Rename `arch/riscv32` directory to `arch/riscv`.
* Require QEMU 4.1 and use `-bios` option on riscv.
* Remove dependence of `cargo-xbuild`.

### CODE REVIEW

**Comment by jiegec** [comment]
LLVM crashed??

**Comment by jiegec** [comment]
riscv seems crashing:

```
OpenSBI v0.4 (Jul  2 2019 11:53:53)
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name          : QEMU Virt Machine
Platform HART Features : RV64ACDFIMSU
Platform Max HARTs     : 8
Current Hart           : 0
Firmware Base          : 0x80000000
Firmware Size          : 112 KB
Runtime SBI Version    : 0.1

PMP0: 0x0000000080000000-0x000000008001ffff (A)
PMP1: 0x0000000000000000-0xffffffffffffffff (A,R,W,X)
Hello RISCV! in hart 0, device tree @ 0xffffffffc2200000
Device features NOTIFY_ON_EMPTY | ANY_LAYOUT | RING_INDIRECT_DESC | RING_EVENT_IDX
Hello RISCV! in hart 3, device tree @ 0xffffffffc2200000
Hello RISCV! in hart 1, device tree @ 0xffffffffc2200000
Hello RISCV! in hart 2, device tree @ 0xffffffffc2200000
/ # === BEGIN rCore stack trace ===
#00 PC: 0xFFFFFFFFC0282A7C FP: 0xFFFFFFFFC02FB7B0
#01 PC: 0xFFFFFFFFC02865F4 FP: 0xFFFFFFFFC02FB810
#02 PC: 0xFFFFFFFFC0286554 FP: 0xFFFFFFFFC02FB840
#03 PC: 0xFFFFFFFFC028173A FP: 0xFFFFFFFFC02FB890
#04 PC: 0xFFFFFFFFC02058B4 FP: 0xFFFFFFFFC02FB8B0
#05 PC: 0xFFFFFFFFC0218B7C FP: 0xFFFFFFFFC02FB9D0
#06 PC: 0xFFFFFFFFC023013C FP: 0xFFFFFFFFC02FBE30
#07 PC: 0xFFFFFFFFC022FBC0 FP: 0xFFFFFFFFC02FBEE0
=== END rCore stack trace ===

```

**Comment by wangrunji0408** [comment]
This is an existing bug on multi-core,
but somehow it appears more often after the Rust toolchain upgrade...
In general, it's caused by accessing `Processor` without disabling interrupt.

I have fixed that in https://github.com/rcore-os/rcore-thread/commit/ae1eb7d3ea97d2810bc85ee1bf56a33fea5dc131 and af83913.
You can try it again?

**Comment by jiegec** [comment]
Yeah, it is fixed.

**Comment by jiegec** [comment]
I can reproduce the llvm crash...

**Comment by jiegec** [comment]
Maybe we had to find another nightly version..

**Comment by wangrunji0408** [comment]
I remove `-export-dynamic` from `aarch64.json` and the build success...
```diff
   "pre-link-args": {
     "ld.lld": [
-      "-Tsrc/arch/aarch64/boot/linker.ld",
-      "-export-dynamic"
+      "-Tsrc/arch/aarch64/boot/linker.ld"
     ]
   },
```
But it may break the LKM feature on aarch64?

**Comment by jiegec** [comment]
The building works in my computer now.

**Pull request merged**
